sudo: required
dist: xenial
language: python

git:
  depth: 1
  submodules: true

cache:
  - apt: true
  - pip : true

matrix:
  include:
    - name: "Python 2.7 gcc-8"
      python: 2.7           
      env: CC=gcc-8 CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8

    - name: "Python 3.5 gcc-8"
      python: 3.5           
      env: CC=gcc-8 CXX=g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8

    - name: "Python 3.7 gcc-8 Debug+Coverage"
      python: 3.7           
      env: CC=gcc-8 CXX=g++-8 BUILD_ARGS="--build-type Debug -- -DCODE_COVERAGE=ON" CODE_COVERAGE=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
            -

    - name: "Python 3.7 gcc-7 (deploy on tag)"
      python: 3.7           
      env: CC=gcc-7 CXX=g++-7 DO_DELPLOY=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         #- llvm-toolchain-precise-3.9
      packages:
         - build-essential 
         - cython


# command to install dependencies
install:
- sudo cp .travis/disco.list /etc/apt/sources.list.d/disco.list
- sudo apt update
- if [ "$CODE_COVERAGE" == "1" ];
    sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-8 10;
    then sudo apt install -y lcov;
    gem install coveralls-lcov;
 fi
- sudo apt install libantlr4-runtime-dev antlr4 -y
- pip install -r requirements.txt
- python setup.py build $BUILD_ARGS
- python setup.py install $BUILD_ARGS

script: 
  - python setup.py test $BUILD_ARGS # the scikit-build automatically executes setup.py develop which requires access to installation dir

after_success:
  - lcov --compat-libtool --directory . --capture --output-file coverage.info.raw
  - lcov --remove coverage.info.raw -o coverage.info '/usr/*' './_skbuild/*'
  - coveralls-lcov coverage.info

deploy:
  provider: pypi
  user: nic30
  password:
    secure: jMuoFXUX5kopaE0ezjl6NUtxAmr8SyKpRyqZQtv3TISOCCmyenqeMR3EVckEsslC5NpQOVDQHagevooo2Ysfpu6WaFll+QJgkvB7yvt3ZHNcXj9YITTpjJNmPF58jch5cjb+kFvMvPnvOnbasBtB+KRiV4tmGRXrgP0Qg7mamVnafo3Krq0OY5hAE+fK2WhFfkyZ8xdo1M794mHf9fIRcmT9c9D8cMatYjjbq724g3OJ8wlIWxDfoa012D+G2IdZOd5+aMkNMOPd504ZnUj40T39kVsgXv0kIx42Y/Wz4Om53UT2GwTBllERq4u5nDB6A4NiVTwpx4g9+r6rCjIBtX11bRgMaDCp7Jdn6KWOsKhvQtU4u2ZGUdIRCrIoJj0NInCfedKnF0FqYA4BC7HgbFCIUnpyKxR/uU0Vz7tD/jW4vP5tr4PcgQ2eTRM5eVJZ3dYoxzlFh2MzmjXA4+MamFVCRjmzDdvaBafEvYlyUUq0D2MQ2hMwjyNlcEIKW4eOi2LaVgdwJsKbDQHc66oVDQRRYu77yFW9XGhwFoTEn0km5TTVah0d9JwvqVzWo4R33FexuthR7pHQbIe7Shw6HKpV6JfbLtvYSLLBXK8UGlW7PXYQtAZN81fwZzXd+2RwCr8otJeGzNIHug0HjK4S0CYCx4HNi0qHXOl5B+DiPuw=
  on:
    tags: true
    branch: master
    condition: $DO_DELPLOY = 1



