/*

    In order to create a new unit you have to make new class derived from Unit.

    You can use sphinx-hwt plugin for sphinx document generator
    to generate interactive schematic and documentation.
    Schematic is generated by directive bellow.

    .. hwt-schematic::
    
*/
module subunit0(input a,
        output b
    );

    assign b = a;
endmodule
/*

    .. hwt-schematic::
    
*/
module SimpleSubunit(input a,
        output b
    );

    wire sig_subunit0_a;
    wire sig_subunit0_b;
    subunit0 subunit0_inst (.a(sig_subunit0_a),
        .b(sig_subunit0_b)
        );


    assign b = sig_subunit0_b;
    assign sig_subunit0_a = a;
endmodule
